### ISSUE TITLE
Pulsating text

### ISSUE THREAD

**Issue by bennypowers** [cpsdqs/dash-syntax#1]
Howdy,
When using this syntax theme (with `pristine` UI theme, although the problem is reproducible with other UI themes as well), I experience pulsating text (see attached video). Notice how the pulsating stops when I switch to normal-mode. The pulsating exists when I disable vim-mode-plus, so as far as I can tell it's unique to this theme, and occurs whenever a regular (i.e. input-mode) cursor is displayed.

It's kinda trippy, you know brings me back to my high school days, but also a little distracting :)

![pulse](https://user-images.githubusercontent.com/1466420/30629621-7c31124c-9de5-11e7-864f-375e271fd9d7.gif)

**Comment by c-probably-archived20260718** [comment]
Huh, seems to be an issue with antialiasing in Chrome or something, caused by the smooth cursor blink. The best I can do is add an option to disable the smooth blinking :/
