### ISSUE TITLE
Colors flashing with animated cursor enabled

### ISSUE THREAD

**Issue by hannesfant** [cpsdqs/dash-syntax#2]
Some colours are flashing when the animated cursor setting is enabled.
Here's the bug in action. https://share.hannes.cf/u/41507304146.mp4

**Comment by c-probably-archived20260718** [comment]
That option was added specifically as a workaround for that issue (see #1) because I have no idea how to fix an issue caused by Blink, which I, for some reason, seem to be unable to reproduce.
I guess I'll keep this issue open in case there _is_ a fix.

**Comment by hannesfant** [comment]
Oh, didn't see that one. It can be just me but it start when I updated Atom just recently.
Can be just me not noticing it before the update though.

**Comment by c-probably-archived20260718** [comment]
I just released 0.4.1 with another workaround I found that _might_ have fixed the issue, but I don't know if it actually did anything. Any difference?

**Comment by hannesfant** [comment]
Yep! Works perfectly, atleast for now.

**Comment by c-probably-archived20260718** [comment]
then at least for now this issue will be closed
until a future chrome version comes along breaks it, yay
